# Generated by Django 5.0.6 on 2024-05-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='total_items',
        ),
    ]
