# Generated by Django 5.0.6 on 2024-05-19 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_cartitem_total_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total_items',
            field=models.IntegerField(default=0),
        ),
    ]
