# Generated by Django 5.0.6 on 2024-05-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cartitem_price_alter_cartitem_quantity_ordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variant',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
