# Generated by Django 5.0.6 on 2024-05-26 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cartitem_variant'),
        ('products', '0008_alter_product_variant_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variant',
            new_name='variant_name',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='variant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.productvarianttype'),
        ),
    ]
