# Generated by Django 5.0.6 on 2024-05-26 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_rename_variant_cartitem_variant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant_name',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='variant_type',
        ),
    ]
