# Generated by Django 5.0.6 on 2024-05-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_cartitem_variant_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
