# Generated by Django 5.0.6 on 2024-05-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demo',
            name='age',
        ),
        migrations.AddField(
            model_name='demo',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
