# Generated by Django 5.0.6 on 2024-05-26 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_demo_age_demo_password'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product_image',
            new_name='ProductImage',
        ),
        migrations.RenameModel(
            old_name='SizeVariant',
            new_name='ProductVariant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='color_variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity_variant',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size_variant',
            new_name='variant_type',
        ),
        migrations.RenameField(
            model_name='productvariant',
            old_name='size_name',
            new_name='variant_name',
        ),
        migrations.DeleteModel(
            name='ColorVariant',
        ),
        migrations.DeleteModel(
            name='QuantityVariant',
        ),
    ]
