# Generated by Django 5.0.6 on 2024-05-26 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_productvarianttype_delete_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='variant_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='products.productvarianttype'),
        ),
    ]
